apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mycrds.mycrds.mycompany.com
spec:
  group: mycrds.mycompany.com
  scope: Namespaced
  names:
    plural: mycrds
    singular: mycrd
    kind: MyCrd
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                replicas:
                  type: integer
                port:
                  type: integer
              required: ["image", "replicas", "port"]
            status:
              type: object
              properties:
                state:
                  type: string
                  enum:
                    - Running
                    - Stopped
