apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mycrds.mycrds.mycompany.com
spec:
  group: mycrds.mycompany.com
  scope: Namespaced
  names:
    plural: mycrds
    singular: mycrd
    kind: MyCrd
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                applicationname:
                  type: string
                repourl:
                  type: string
                clustername:
                  type: string
              required: 
                - applicationname
                - repourl
                - clustername
            status:
              type: object
              properties:
                state:
                  type: string
                  enum:
                    - Pending
                    - Running
                    - Failed
                    - Succeeded
